# Setup
```{r setup}
    rm(list = ls())

    # knitr options
    knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE, fig.align = 'center',
                          fig.width = 10, fig.height = 7) 
    
    # libraries 
    library(tidyverse)
    library(dplyr)
    library(ggplot2)
    library(sp)
    library(raster)
    library(rgeos)
    library(rgdal)
    library(sf)
    library(googledrive)
    library(units)
    library(nngeo)
    library(magrittr)
    
    # data
    ## gpkg - ESPG 4283 (GDA94)
    grid <- readRDS("./data/gpkg/2.0_Sites_4283.gpkg")
    
    dat <- read_csv("data/01_data/1.2_dat.csv") %>% 
      filter(ActivityType == "Extractive" & SiteType == "Boat" & (str_detect(Site, "BR")))
    
    # dat <- read_csv("data/01_data/1.2_dat.csv") %>% filter(FishingType %in% c("Casting", "Demersal"))
    
    BR <- readRDS("./data/gpkg/2.1_BRtrips.gpkg") %>% st_transform(crs = 4283)# from BRtrips.R
    
    hol <- read_csv("./data/RAW/Holidays.csv") %>% 
      mutate(Date = as.POSIXct(Date, format = "%d/%m/%y"))
    
    boat_perf <- read_csv("./data/RAW/boatengines.csv")
    
    fuel <- read_csv("./data/RAW/Monthly-ULP-prices-Gascoyne-201507-202109.csv")
    
    vott <- read.csv("./data/RAW/VOTT.csv")
    
    # models
    cons_mod <- readRDS("./models/cons_mod.rda")
    sp_mod <- readRDS("./models/sp_mod.rda")
    
    source("./functions/genFunc.R") # function for smple weighting
    
     sf_use_s2(FALSE)
```

# Joining external data
## Fuel
```{r}
fuel %<>%
  mutate(TripMonth = gsub("[^a-zA-Z]", "", Month)) %>%
  mutate(numYear = as.numeric(paste0("20", as.numeric(gsub("[^0-9]", "", Month))))) %>%
  mutate(cost = Average/100)

dat %<>% left_join(fuel[, c("TripMonth", "numYear", "cost")])

rm(fuel)
```

## Boat specs
```{r}
# Boat Length - filling in NAs with model (not worth it)
# dat %<>% rename(PartySize = Party)
# tmp <- dat %>% filter(is.na(BoatLength) & SiteType == "Boat") %>% dplyr::select(TripID, BoatLength, PartySize)
# unique(tmp$Party)

# Filling Party size where it exists
# tmp %<>% mutate(PartySize = ifelse(PartySize %in% c("6f", "Two couples 2 kids", "3F, 2M, 1b"), 6, 
#                                     ifelse(PartySize %in% c("2f", "2 dudes", "2males", "Couple", "1M 1b"), 2, 
#                                            ifelse(PartySize %in% c("2f, 2kids", "4 friends", "2 couples", "4 mates", "1m1b", "Couple, 2g", "Couple,2g 1b"), 4,
#                                                   ifelse(PartySize %in% c("Man", "1M"), 1, 
#                                                          ifelse(PartySize %in% c("2b1g", "3M", "3m"), 3, NA))))))

      # tmp$lm_bl <- predict(bl_mod, tmp) # predicting boatlength using party size
      # tmp$lm_bl <- round(as.numeric(tmp$lm_bl), 2)
      # dat %<>%  left_join(tmp[, c("TripID", "lm_bl")])
      
      # dat %<>% 
      #   mutate(BoatLength = ifelse(SiteType == "Boat" & !is.na(lm_bl), lm_bl, BoatLength)) %>% # appending modelled boat length
      #   mutate(BoatLength = ifelse(SiteType == "Boat" & is.na(BoatLength), mean(BoatLength, na.rm = T), BoatLength)) # filling rest of boat length with NAs
        
 # Consumption
boat_perf %<>%  
  filter(kmperh < 4000) %>% 
    mutate(boat_size2L = ifelse(boatlength <= 3.75, "S", "L")) %>%
  mutate(boat_size3L = ifelse(boatlength <= 3.75, "S", 
                            ifelse(boatlength <= 6.75, "M", "L"))) %>% 
  mutate(cons = kmperl/nEngines)

boat3L <- boat_perf %>% 
  group_by(boat_size3L) %>% 
  summarise(sp3l = median(kmperh),
            cons3l = median(cons))

boat2L <- boat_perf %>% 
  group_by(boat_size2L) %>% 
  summarise(sp2l = median(kmperh),
            cons2l = median(cons))
  
dat %<>% 
   mutate(BoatLength = ifelse(is.na(BoatLength), mean(BoatLength, na.rm = TRUE), BoatLength)) %>%
  mutate(boat_size2L = ifelse(BoatLength <= 3.75, "S", "L")) %>%
  mutate(boat_size3L = ifelse(BoatLength <= 3.75, "S", 
                            ifelse(BoatLength <= 6.75, "M", "L"))) %>% 
  left_join(boat2L[, c("boat_size2L", "cons2l", "sp2l")], by = "boat_size2L") %>% 
  left_join(boat3L[, c("boat_size3L", "cons3l", "sp3l")], by = "boat_size3L")

dat %<>% 
  mutate(cons_flt = median(boat_perf$cons)) %>% 
  mutate(sp_flt = median(boat_perf$kmperh))
  

# modeled consumption
 tmp <- dat %>% 
        dplyr::select(BoatLength) %>% 
        rename(boatlength = BoatLength) %>% 
        st_drop_geometry()
      
      gam_cons <- predict(cons_mod, tmp)
      gam_sp <- predict(sp_mod, tmp)
      
      dat$gam_cons <- as.numeric(gam_cons)
      dat$gam_sp <- as.numeric(gam_sp)
      
rm( boat_perf, boat2L, boat3L, gam_cons, cons_mod, sp_mod, gam_sp)
```

## VOTT
```{r}
# Append census data
    dat %<>% left_join(vott[, c("Postcode", "ann_inc_21", "VOTT_21")]) 

# Model income ~ boat size to fill NAs
## Make small modelling data set
    tmp <- dat %>% 
      filter(!is.na(ann_inc_21) & !is.na(BoatLength)) %>% 
      mutate(ann_inc_21 = as.numeric(ann_inc_21))

## Linear model
    lm_ann_inc <- lm(ann_inc_21 ~ BoatLength, data = tmp)

## Check 
      ggplot(dat = tmp, aes(x = ann_inc_21, y = BoatLength)) +
        geom_point() +
        stat_smooth(method = "lm")

## Predict to data 
      dat$lm_ann_inc <- predict(lm_ann_inc, dat)

# Calculate vott from annual income
      dat %<>%
        mutate(ann_inc = ifelse(!is.na(ann_inc_21), ann_inc_21, lm_ann_inc)) %>% 
        mutate(ann_inc = ifelse(is.na(ann_inc), mean(ann_inc, na.rm = T), ann_inc)) %>% 
        mutate(vott = round(ann_inc/(38*52), 2))


rm(tmp, lm_ann_inc, vott)
```

# Filtering
All data filters have to be done before making the choice set.
```{r}
    dat %<>% 
      filter(ActivityType == "Extractive") %>% # filtering activity
      filter(str_detect(Site, "BR")) %>% 
      filter(!is.na(UseLat), !is.na(UseLong)) %>% # filtering empty coords
      st_as_sf(coords = c("UseLong", "UseLat"), crs = 4283) %>%  ## make sf object
      rename(dat_geom = geometry)
      
    # need one trip per row (longest site visited on trip)
    dat %<>% 
      group_by(PersonID, TripID) %>% 
      slice(which.max(decDuration)) %>% 
      ungroup() 
    
      #'[#VALIDATE: TRUE, no duplicated trip IDs)]
      identical((which(duplicated(dat$TripID) == TRUE)), integer(0)) == TRUE
```

# Weighting
```{r}
    # for getting survey weights
    dat <- dat %>%
      mutate(SurveyDate_posix = as.POSIXct(SurveyDate, format = "%m/%d/%Y %H:%M:%S") +
               8*60*60) %>%
      mutate(Time = format(SurveyDate_posix, "%p")) %>%
      mutate(DayType = weekdays(SurveyDate_posix, abbreviate = TRUE)) %>%
      mutate(DayType = ifelse(DayType %in% c("Sat", "Sun"), "Weekend", "Weekday")) %>%
      mutate(SurveyDate_posix = as.POSIXct(SurveyDate, format = "%m/%d/%Y")) %>%
      mutate(Hol = ifelse(SurveyDate_posix %in% hol$Date, hol$Holiday, NA)) %>%
      mutate(DayType = ifelse(Hol %in% "public", "Weekend", DayType)) %>%
      mutate(Hol = ifelse(Hol %in% "school", 1, 0)) %>%
      unite("psuid", c(SurveyDate_posix, Time), remove = F, sep = " ")

    
    # # calculating even weights
    # dat <- even_weights(df = dat, psuid = psuid, w_col = "Time")
    dat <- even_weights(df = dat, psuid = psuid, w_col = "Site")

    # calculate uneven weights
    # Holidays
    nYr <- n_distinct(dat$numYear)
    
    nhol <- hol %>% filter(Holiday == "school")  %>% nrow()
    w_hol1 = nhol/(365*nYr)
    w_hol0 = ((365*nYr) - nhol)/(365*nYr)

    ## checkpoint: == 1
    w_hol1 + w_hol0

    # append
    dat %<>% mutate(w_hol = ifelse(Hol %in% 1, w_hol1, w_hol0))

    # DayType
    wdat <- dat %>% distinct(psuid, .keep_all = TRUE)
    daytype_smpl <- as.data.frame(table(wdat$DayType)) %>%
      mutate(w = ifelse(Var1 %in% "Weekend", Freq/(2*52), Freq/(5*52))) %>%
      mutate(w_daytype = w/sum(w)) %>% # scaling
      rename(DayType = Var1)

    ## checkpoint: == 1
    sum(daytype_smpl$w_daytype)

    # append
    dat %<>% left_join(daytype_smpl[, c("DayType", "w_daytype")])

    # overall weight
    dat %<>% mutate(smpl_w = w_Site*w_hol*w_daytype)
    
    rm(hol, wdat, daytype_smpl, w_hol0, w_hol1, nhol, nYr)
```

# Choice set
```{r choice set}
# make a grid (no replications across boat ramps)
sm_grid <- grid %>%
  dplyr::select(gridid, grid_geom) %>%
  distinct(gridid, .keep_all = TRUE)

which(duplicated(sm_grid$gridid)) # should be none

# Writing choice set
# choice <- sites %>% dplyr::select(gridID_alt, geom)
# st_write(choice, "./data/gpkg/2.1_ChoiceSetQ_4283.gpkg", append = FALSE) # need to write with st_write to open in QGISRUMs
# saveRDS(sites, "./data/gpkg/2.1_ChoiceSet_4283.gpkg")

# Appending visited grids to data
dat %<>% 
  st_join(sm_grid, left = T, join = st_intersects) %>% 
  rename(gridid_vis = gridid)

# Selecting data attributes
dat %<>% 
  # rename(gridID_vis = gridID_alt) %>% 
  dplyr::select(TripID, PersonID, gridid_vis, Site, TripDate, MedianTime, BoatLength, cost, smpl_w, Postcode, cons_flt, sp_flt, cons2l, sp2l, cons3l, sp3l, gam_cons, gam_sp, vott, ann_inc, KeptUndam, Dem, Dem_bin, Start_hr, BaitLure, Age, exTimes12m, TripMonth, numYear, decDuration) %>% 
  distinct() %>% 
  mutate(RampID = ifelse(Site %in% "BundegiBR", "73", NA),
         RampID = ifelse(Site %in% "CoralBayBR", "72", RampID),
         RampID = ifelse(Site %in% "ExmouthBR", "85", RampID),
         RampID = ifelse(Site %in% "TantabiddiBR", "87", RampID)) %>% 
  mutate(UseLong = st_coordinates(dat_geom)[,1]) %>% 
  mutate(UseLat = st_coordinates(dat_geom)[,2]) %>% 
  as.data.frame()

    #'[#VALIDATE: TRUE, there are no unassigned gridIDs]
    
    identical((which(is.na(dat$gridID_vis) == TRUE)), integer(0)) == TRUE
    
 # Make full choice set
    t1 <- nrow(dat) # copying original data test join

    dat <- inner_join(dat, grid, by = "RampID") 
    
    #'[#VALIDATE: TRUE, number of sites * number of trips == nrow(dat), unless sites have been removed eg. beach launching sites]
    
    t1*nrow(sm_grid) == nrow(dat)
```


# Choice and travel cost ($0.54/km)
```{r choice and travel cost}

      dat <- dat %>%
        rename(gridid_alt = gridid) %>% 
        # filter(!is.na(Postcode)) %>% 
        mutate(choice = ifelse(gridid_vis == gridid_alt, 1, 0)) %>%
        # mutate(land_fc = round(as.numeric((cost/(100/12))*accom_br), 2)*2) %>% 
        # mutate(water_fc = round(as.numeric((cost/consump)*km_BR), 2)*2) %>% #changing fuel&cost
        # mutate(lm_fc = round(as.numeric((cost/lm_cons)*km_BR), 2)*2) %>% 
        mutate(l_fc2l = round(as.numeric((cost/cons2l)*l_km_br), 2)) %>% 
        mutate(nl_fc2l = round(as.numeric((cost/cons2l)*nl_km_br), 2)) %>% 
  
        mutate(l_fc3l = round(as.numeric((cost/cons3l)*l_km_br), 2)) %>% 
        mutate(nl_fc3l = round(as.numeric((cost/cons3l)*nl_km_br), 2)) %>% 
  
        mutate(l_trvlTime2l = round(as.numeric(l_km_br/sp2l, 2))) %>%
        mutate(nl_trvlTime2l = round(as.numeric(nl_km_br/sp2l, 2))) %>%
  
        mutate(l_trvlTime3l = round(as.numeric(l_km_br/sp3l), 2)) %>%
        mutate(nl_trvlTime3l = round(as.numeric(nl_km_br/sp3l), 2)) %>%
  
        mutate(l_trp_vott2l = round(as.numeric(vott*l_trvlTime2l), 2)*2) %>%
        mutate(nl_trp_vott2l = round(as.numeric(vott*nl_trvlTime2l), 2)*2) %>%
  
        mutate(l_trp_vott3l = round(as.numeric(vott*l_trvlTime3l), 2)*2) %>%
        mutate(nl_trp_vott3l = round(as.numeric(vott*nl_trvlTime3l), 2)*2) %>%
  
        mutate(l_tc2l = round(as.numeric(l_fc2l + l_trp_vott2l), 2)) %>% 
        mutate(nl_tc2l = round(as.numeric(nl_fc2l + nl_trp_vott2l), 2)) %>% 
  
        mutate(l_tc3l = round(as.numeric(l_fc3l + l_trp_vott3l), 2)) %>% 
        mutate(nl_tc3l = round(as.numeric(nl_fc3l + nl_trp_vott3l), 2))

dat <- dat %>% 
  mutate(centroidLong = st_coordinates(centroid)[,1]) %>% # need this is using dynamic variables
  mutate(centroidLat = st_coordinates(centroid)[,2])
  
dat_rum_df <- dat %>% dplyr::select(-c(centroid, br_geom, grid_geom, dat_geom))
```

# Save output
```{r save}
  write_csv(dat_rum_df, "./data/02_data/2.1_dat.csv")
  saveRDS(dat, paste0("./data/gpkg/sims/2.1_dat.gpkg")) # script 3.1

# saveRDS(dat, "./data/gpkg/2.1_dat.gpkg")
```
